// src/routes/doc/[id]/+page.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';
  import { pagesStore } from '$lib/stores/pages.svelte';
  import Editor from '$lib/components/Editor.svelte';
  import type { JSONContent } from '@tiptap/core';
  import { Globe, Lock, Smile } from 'lucide-svelte';

  const id = $derived($page.params.id);
  const currentPage = $derived(pagesStore.getById(id));

  // Title editing
  let titleEl: HTMLDivElement = $state() as HTMLDivElement;
  let saveTitleTimer: ReturnType<typeof setTimeout>;

  function onTitleInput(e: Event) {
    const text = (e.target as HTMLDivElement).innerText;
    clearTimeout(saveTitleTimer);
    saveTitleTimer = setTimeout(() => {
      pagesStore.updatePage(id, { title: text.trim() || 'Untitled' });
    }, 400);
  }

  function onTitleKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter') {
      e.preventDefault();
      // Focus the editor on Enter from title
      const editorEl = document.querySelector('.ProseMirror') as HTMLElement | null;
      editorEl?.focus();
    }
  }

  async function handleContentUpdate(content: JSONContent) {
    await pagesStore.updateContent(id, content);
  }

  async function togglePublic() {
    const publicId = await pagesStore.togglePublic(id);
    if (publicId) {
      const url = `${window.location.origin}/p/${publicId}`;
      navigator.clipboard.writeText(url).catch(() => {});
    }
  }

  // Emoji picker (simple prompt for now)
  async function changeIcon() {
    const icon = window.prompt('Enter an emoji for the page icon:', currentPage?.icon ?? '');
    if (icon !== null && currentPage) {
      await pagesStore.updatePage(id, { icon: icon.trim().slice(0, 2) });
    }
  }
</script>

{#if !pagesStore.initialized}
  <div class="flex items-center justify-center min-h-screen">
    <div class="w-6 h-6 border-2 border-violet-400 border-t-transparent rounded-full animate-spin"></div>
  </div>
{:else if !currentPage}
  <div class="flex flex-col items-center justify-center min-h-screen gap-4">
    <div class="text-5xl">🔍</div>
    <p class="text-neutral-500 dark:text-neutral-400 text-sm">Page not found</p>
    <a href="/" class="text-sm text-violet-600 hover:underline">← Back to home</a>
  </div>
{:else}
  <div class="min-h-screen">
    <!-- Toolbar -->
    <div class="sticky top-0 z-20 flex items-center justify-end gap-2 px-6 py-2 border-b border-neutral-100 dark:border-neutral-800 bg-white/80 dark:bg-neutral-900/80 backdrop-blur-sm">
      <button
        onclick={togglePublic}
        class="flex items-center gap-1.5 px-2.5 py-1 text-xs rounded-md transition-colors {currentPage.isPublic
          ? 'bg-green-50 dark:bg-green-900/30 text-green-600 dark:text-green-400 hover:bg-green-100 dark:hover:bg-green-900/50'
          : 'text-neutral-500 dark:text-neutral-400 hover:bg-neutral-100 dark:hover:bg-neutral-800'}"
        title={currentPage.isPublic ? 'Click to make private' : 'Click to share publicly'}
      >
        {#if currentPage.isPublic}
          <Globe size={13} />
          Public · Copy link
        {:else}
          <Lock size={13} />
          Private
        {/if}
      </button>
    </div>

    <!-- Page header -->
    <div class="px-[96px] pt-16 pb-2 max-w-4xl mx-auto">
      <!-- Icon -->
      <button
        onclick={changeIcon}
        class="text-5xl leading-none mb-3 hover:bg-neutral-100 dark:hover:bg-neutral-800 rounded-lg p-1 -ml-1 transition-colors inline-block"
        title="Change icon"
        aria-label="Change page icon"
      >
        {currentPage.icon || '📄'}
      </button>

      <!-- Title -->
      <div
        bind:this={titleEl}
        contenteditable="true"
        class="text-4xl font-bold outline-none text-neutral-900 dark:text-neutral-100 leading-tight mb-1 empty:before:content-['Untitled'] empty:before:text-neutral-300 dark:empty:before:text-neutral-600 cursor-text"
        oninput={onTitleInput}
        onkeydown={onTitleKeydown}
        role="textbox"
        tabindex="0"
        aria-label="Page title"
        aria-multiline="false"
        spellcheck="false"
      >{currentPage.title}</div>
    </div>

    <!-- TipTap editor -->
    <Editor
      content={currentPage.content}
      onUpdate={handleContentUpdate}
      editable={true}
    />
  </div>
{/if}

// app/doc/[id]/page.tsx
"use client"

import { useState, useEffect, useCallback, useRef, use } from "react"
import { useRouter } from "next/navigation"
import { Editor } from "@/components/editor/editor"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Separator } from "@/components/ui/separator"
import {
  ArrowLeft,
  Share2,
  Globe,
  Lock,
  Trash2,
  Check,
  Moon,
  Sun,
} from "lucide-react"
import { useTheme } from "next-themes"
import { toast } from "sonner"

interface Document {
  id: string
  title: string
  icon: string
  content: Record<string, unknown> | null
  isPublic: boolean
  updatedAt: string
}

export default function DocPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params)
  const router = useRouter()
  const { resolvedTheme, setTheme } = useTheme()
  const [doc, setDoc] = useState<Document | null>(null)
  const [loading, setLoading] = useState(true)
  const [title, setTitle] = useState("")
  const [icon, setIcon] = useState("📄")
  const [saved, setSaved] = useState(false)
  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null)

  const fetchDoc = useCallback(async () => {
    const res = await fetch(`/api/documents/${id}`)
    if (res.ok) {
      const data = await res.json()
      setDoc(data)
      setTitle(data.title)
      setIcon(data.icon)
    } else {
      router.push("/")
    }
    setLoading(false)
  }, [id, router])

  useEffect(() => {
    fetchDoc()
  }, [fetchDoc])

  const save = useCallback(
    async (updates: Partial<Document>) => {
      await fetch(`/api/documents/${id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(updates),
      })
      setSaved(true)
      setTimeout(() => setSaved(false), 2000)
    },
    [id]
  )

  const handleContentChange = useCallback(
    (content: Record<string, unknown>) => {
      if (saveTimer.current) clearTimeout(saveTimer.current)
      saveTimer.current = setTimeout(() => {
        save({ content })
      }, 800)
    },
    [save]
  )

  const handleTitleBlur = () => {
    if (title !== doc?.title) save({ title })
  }

  const handleTitleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") (e.target as HTMLInputElement).blur()
  }

  const togglePublic = async () => {
    const updated = !doc?.isPublic
    setDoc((prev) => (prev ? { ...prev, isPublic: updated } : prev))
    await save({ isPublic: updated })
    if (updated) {
      const url = `${window.location.origin}/p/${id}`
      await navigator.clipboard.writeText(url).catch(() => {})
      toast.success("Public link copied to clipboard!", {
        description: url,
      })
    } else {
      toast("Page is now private")
    }
  }

  const copyShareLink = async () => {
    const url = `${window.location.origin}/p/${id}`
    await navigator.clipboard.writeText(url).catch(() => {})
    toast.success("Link copied!", { description: url })
  }

  const deleteDoc = async () => {
    if (!confirm("Delete this page permanently?")) return
    await fetch(`/api/documents/${id}`, { method: "DELETE" })
    router.push("/")
  }

  if (loading) {
    return (
      <div className="flex h-screen items-center justify-center">
        <div className="h-6 w-6 animate-spin rounded-full border-2 border-primary border-t-transparent" />
      </div>
    )
  }

  if (!doc) return null

  return (
    <div className="flex h-screen flex-col bg-background">
      <header className="flex h-12 shrink-0 items-center gap-2 border-b px-4">
        <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => router.push("/")}>
          <ArrowLeft className="h-4 w-4" />
        </Button>

        <div className="flex flex-1 items-center gap-2 overflow-hidden">
          <button
            className="shrink-0 text-lg leading-none"
            onClick={() => {
              const emoji = window.prompt("Choose an emoji icon", icon)
              if (emoji) {
                setIcon(emoji)
                save({ icon: emoji })
              }
            }}
          >
            {icon}
          </button>
          <Input
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            onBlur={handleTitleBlur}
            onKeyDown={handleTitleKeyDown}
            className="h-7 flex-1 border-none bg-transparent p-0 text-sm font-medium shadow-none focus-visible:ring-0"
            placeholder="Untitled"
          />
        </div>

        <div className="flex shrink-0 items-center gap-1">
          {saved && (
            <span className="flex items-center gap-1 text-xs text-muted-foreground">
              <Check className="h-3 w-3" />
              Saved
            </span>
          )}

          <Button
            variant="ghost"
            size="sm"
            className="h-8 gap-1.5 text-xs"
            onClick={togglePublic}
          >
            {doc.isPublic ? (
              <>
                <Globe className="h-3.5 w-3.5 text-green-500" />
                Public
              </>
            ) : (
              <>
                <Lock className="h-3.5 w-3.5" />
                Private
              </>
            )}
          </Button>

          {doc.isPublic && (
            <Button variant="outline" size="sm" className="h-8 gap-1.5 text-xs" onClick={copyShareLink}>
              <Share2 className="h-3.5 w-3.5" />
              Copy link
            </Button>
          )}

          <Button
            variant="ghost"
            size="icon"
            className="h-8 w-8"
            onClick={() => setTheme(resolvedTheme === "dark" ? "light" : "dark")}
          >
            {resolvedTheme === "dark" ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
          </Button>

          <Button variant="ghost" size="icon" className="h-8 w-8 text-destructive hover:text-destructive" onClick={deleteDoc}>
            <Trash2 className="h-4 w-4" />
          </Button>
        </div>
      </header>

      <Separator />

      <main className="flex-1 overflow-y-auto">
        <div className="mx-auto max-w-3xl px-8 py-10">
          <h1 className="mb-6 text-4xl font-bold tracking-tight text-foreground/90 outline-none">
            {icon} {title || "Untitled"}
          </h1>
          <Editor content={doc.content} onChange={handleContentChange} />
        </div>
      </main>
    </div>
  )
}
