// src/routes/p/[id]/+page.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';
  import { pagesStore } from '$lib/stores/pages.svelte';
  import PublicHeader from '$lib/components/PublicHeader.svelte';
  import Editor from '$lib/components/Editor.svelte';
  import { onMount } from 'svelte';

  const publicId = $derived($page.params.id);
  let publicPage = $state<ReturnType<typeof pagesStore.getByPublicId>>(undefined);
  let duplicating = $state(false);

  $effect(() => {
    if (pagesStore.initialized) {
      publicPage = pagesStore.getByPublicId(publicId);
    }
  });

  async function duplicate() {
    if (!publicPage || duplicating) return;
    duplicating = true;
    try {
      const newPage = await pagesStore.duplicatePage(publicPage.id);
      goto(`/doc/${newPage.id}`);
    } finally {
      duplicating = false;
    }
  }
</script>

<svelte:head>
  {#if publicPage}
    <title>{publicPage.title || 'Untitled'} · Notion Clone</title>
  {:else}
    <title>Page not found · Notion Clone</title>
  {/if}
</svelte:head>

{#if !pagesStore.initialized}
  <div class="flex items-center justify-center min-h-screen">
    <div class="w-6 h-6 border-2 border-violet-400 border-t-transparent rounded-full animate-spin"></div>
  </div>
{:else if !publicPage}
  <div class="flex flex-col items-center justify-center min-h-screen gap-4 px-4 text-center">
    <div class="text-6xl">🔒</div>
    <h1 class="text-xl font-semibold text-neutral-800 dark:text-neutral-100">Page not found</h1>
    <p class="text-neutral-500 dark:text-neutral-400 text-sm">This page is private or doesn't exist.</p>
    <a href="/" class="text-sm text-violet-600 hover:underline mt-2">Go to workspace →</a>
  </div>
{:else}
  <!-- Public header with duplicate button -->
  <PublicHeader page={publicPage} onDuplicate={duplicate} />

  <!-- Read-only editor -->
  <div class="min-h-screen">
    <div class="px-[96px] pt-12 pb-4 max-w-4xl mx-auto">
      <div class="text-5xl leading-none mb-3">{publicPage.icon || '📄'}</div>
      <h1 class="text-4xl font-bold text-neutral-900 dark:text-neutral-100 leading-tight mb-1">
        {publicPage.title || 'Untitled'}
      </h1>
    </div>

    <Editor
      content={publicPage.content}
      editable={false}
    />
  </div>

  {#if duplicating}
    <div class="fixed inset-0 z-50 bg-black/30 flex items-center justify-center">
      <div class="bg-white dark:bg-neutral-800 rounded-xl px-6 py-4 shadow-xl flex items-center gap-3">
        <div class="w-5 h-5 border-2 border-violet-500 border-t-transparent rounded-full animate-spin"></div>
        <span class="text-sm font-medium text-neutral-700 dark:text-neutral-200">Duplicating page…</span>
      </div>
    </div>
  {/if}
{/if}

// app/p/[id]/page.tsx
import { getDocumentById } from "@/lib/db"
import { Editor } from "@/components/editor/editor"
import { notFound } from "next/navigation"
import { Globe, FileText } from "lucide-react"

export default async function PublicPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const doc = getDocumentById(id)

  if (!doc) notFound()
  if (!doc.isPublic) {
    return (
      <div className="flex h-screen flex-col items-center justify-center gap-4 bg-background">
        <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-muted">
          <FileText className="h-7 w-7 text-muted-foreground" />
        </div>
        <h1 className="text-xl font-semibold">This page is private</h1>
        <p className="text-sm text-muted-foreground">The owner hasn&apos;t made this page public.</p>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-10 border-b bg-background/80 backdrop-blur">
        <div className="mx-auto flex max-w-3xl items-center gap-2 px-8 py-3">
          <span className="text-xl">{doc.icon}</span>
          <h1 className="flex-1 truncate text-sm font-medium">{doc.title}</h1>
          <span className="flex items-center gap-1 rounded-full bg-green-500/10 px-2.5 py-0.5 text-xs text-green-600 dark:text-green-400">
            <Globe className="h-3 w-3" />
            Public
          </span>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-8 py-10">
        <h1 className="mb-6 text-4xl font-bold tracking-tight">
          {doc.icon} {doc.title}
        </h1>
        <Editor content={doc.content} editable={false} />
      </main>

      <footer className="mt-16 border-t py-6 text-center text-xs text-muted-foreground">
        Made with Notion Clone on Replit
      </footer>
    </div>
  )
}
